In [1]:
pip install nbconvert

Note: you may need to restart the kernel to use updated packages.


In [45]:
# State-tranistion Model
p_st1 = 0.1;            # p(x+2 at t | x at t-1) = 10% it moves 2 meters
p_st2 = 0.05;           # p(x at t | x at t-1) = 5% it doesn't move
p_st3 = 0.05;           # p(x-1 at t | x at t-1) = 5% it moves backward by 1 meters
p_st4 = 0.8;            # p(x+1 at t | x at t-1) = 80% it moves 1 meter forward

In [46]:
#Measuerment Model
p_m1 = 0.9;             #P(pos = x | x=x) = 90%
p_m2 = 0.1;             #P(pos =x | x!=x) = 10%

In [68]:
# At t = 0, Bel(x=1,2,3..100) = 1/100  = 0.01
bel_x0 = np.full(100,0.01);

In [110]:
# At t = 1, it makes a motion 
bel_hat_x1 = np.dot(arr,bel_x0);

In [131]:
#measurement model matrix
p_m = np.full(100,0.1)

In [132]:
p_m[1] = 0.9

In [133]:
p_m

array([0.1, 0.9, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
       0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [142]:
bel_x1_wo_n = p_m*bel_hat_x1;

In [125]:
bel_hat_x1

array([0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01,
       0.01])

In [143]:
n = (1/bel_x1_wo_n.sum())
n

9.259259259259256

In [145]:
bel_x1 = n*bel_x1_wo_n
bel_x1

array([0.00925926, 0.08333333, 0.00925926, 0.00925926, 0.00925926,
       0.00925926, 0.00925926, 0.00925926, 0.00925926, 0.00925926,
       0.00925926, 0.00925926, 0.00925926, 0.00925926, 0.00925926,
       0.00925926, 0.00925926, 0.00925926, 0.00925926, 0.00925926,
       0.00925926, 0.00925926, 0.00925926, 0.00925926, 0.00925926,
       0.00925926, 0.00925926, 0.00925926, 0.00925926, 0.00925926,
       0.00925926, 0.00925926, 0.00925926, 0.00925926, 0.00925926,
       0.00925926, 0.00925926, 0.00925926, 0.00925926, 0.00925926,
       0.00925926, 0.00925926, 0.00925926, 0.00925926, 0.00925926,
       0.00925926, 0.00925926, 0.00925926, 0.00925926, 0.00925926,
       0.00925926, 0.00925926, 0.00925926, 0.00925926, 0.00925926,
       0.00925926, 0.00925926, 0.00925926, 0.00925926, 0.00925926,
       0.00925926, 0.00925926, 0.00925926, 0.00925926, 0.00925926,
       0.00925926, 0.00925926, 0.00925926, 0.00925926, 0.00925926,
       0.00925926, 0.00925926, 0.00925926, 0.00925926, 0.00925

In [146]:
bel_hat_x2 = np.dot(arr,bel_x1)

In [ ]:
bel_x2 = n*

In [103]:
arr[98][:]

array([0.8 , 0.8 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.1 , 0.05,
       0.05])

In [104]:
bel_x1 = n*bel_hat_x1*(p_m1+p_m2);

NameError: name 'n' is not defined

In [22]:
bel_x1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [105]:
arr = np.zeros((100,100))


In [106]:
arr[0][0]=0.05
arr[0][99]=0.1
arr[0][1]=0.05
arr[0][2]=0.8

arr[98][0]=0.8

arr[99][98]=0.1
arr[99][99]=0.05
arr[99][0]=0.05
arr[99][1]=0.8

arr[98][97]=0.1
arr[98][98]=0.05
arr[98][99]=0.05
arr[98][0]=0.8


In [107]:
arr

array([[0.05, 0.05, 0.8 , ..., 0.  , 0.  , 0.1 ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.8 , 0.  , 0.  , ..., 0.1 , 0.05, 0.05],
       [0.05, 0.8 , 0.  , ..., 0.  , 0.1 , 0.05]])

In [108]:
for i in range(1,98):
    arr[i][i-1]=0.1
    arr[i][i]=0.05
    arr[i][i+1]=0.05
    arr[i][i+2]=0.8


In [109]:
arr


array([[0.05, 0.05, 0.8 , ..., 0.  , 0.  , 0.1 ],
       [0.1 , 0.05, 0.05, ..., 0.  , 0.  , 0.  ],
       [0.  , 0.1 , 0.05, ..., 0.  , 0.  , 0.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.05, 0.05, 0.8 ],
       [0.8 , 0.  , 0.  , ..., 0.1 , 0.05, 0.05],
       [0.05, 0.8 , 0.  , ..., 0.  , 0.1 , 0.05]])